---
apiVersion: v1
kind: Service
metadata:
  name: edu-telegram-bot
  namespace: edu
spec:
  selector:
    app: edu-telegram-bot
  ports:
    - port: 3033
      name: edu-telegram-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-telegram-bot
  namespace: edu
  labels:
    app: edu-telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
        app: edu-telegram-bot
  template:
    metadata:
      labels:
        app: edu-telegram-bot
    spec:
      containers:
        - name: main
          imagePullPolicy: Always
          image: harbor.ru/edu/bot_telegram:latest
          resources:
            requests:
              memory: 512Mi
              cpu: 1000m
            limits:
              memory: 1Gi
              cpu: 1000m
          ports:
            - containerPort: 3033
